GET http://localhost:3000/products?page=10&limit=20

###
POST http://localhost:3000/users/create

###
GET http://localhost:3000/products/edit

###
GET http://localhost:3000/products/123

###
POST http://localhost:3000/products/new
Content-Type: application/json

{
    "name": "Microondas",
    "price": 399,
    "category": "kitchen",
    "stock": 100
}

#################
## PRUEBAS API ##
#################

GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/price/100

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Boli rojo",
    "description": "No se gasta",
    "category": "office",
    "price": 2,
    "stock": 200,
    "available": false
}

###
PUT http://localhost:3000/api/products/626ae045f3be178566f6bb2d
Content-Type: application/json

{
    "price": 2500,
    "stock": 100,
    "available": true
}

###
DELETE http://localhost:3000/api/products/626ae045f3be178566f6bb2d


###############
## API USERS ##
###############

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Manolo",
    "email": "manolo@gmail.com",
    "username": "manu",
    "password": "12345",
    "age": 65,
    "active": true
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "manolo@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/articles
Content-Type: application/json

{
    "title": "Título 1",
    "text": "Texto 1",
    "createdAt": "2022-05-12",
    "category": "sports",
    "author": "Laura"
}





####
POST http://localhost:3000/api/departments
Content-Type: application/json

{
    "name": "oficina",
    "description": "material de oficina",
    "created_at": "2022-06-23 14:34"
}

###
POST http://localhost:3000/api/departments/add-product
Content-Type: application/json

{
    "product_id": "62b4a2cb88fc4afce5a8f15b",
    "department_id": "62b4a1012314174315b752de"
}

###
GET http://localhost:3000/api/departments